config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  description         :text             not null
#  name                :string           not null
#  overall_rating      :float
#  tumbnail_image_path :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_products_on_name  (name) UNIQUE
#
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :description, presence: true
  validates :name, uniqueness: true

  def recalculate_overall_rating
    with_lock do
      new_rating = reviews.sum(:rating).to_f / reviews.count
      update(overall_rating: new_rating)
    end
  end
end

app/models/review.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reviews
#
#  id             :integer          not null, primary key
#  rating         :integer          not null
#  reviewer_name  :string           not null
#  written_review :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  product_id     :integer
#
# Indexes
#
#  index_reviews_on_product_id  (product_id)
#
# Foreign Keys
#
#  product_id  (product_id => products.id)
#
class Review < ApplicationRecord
  belongs_to :product

  validates :rating, :reviewer_name, presence: true
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 }

  after_commit :recalculate_product_overall_rating

  private

  def recalculate_product_overall_rating
    product.recalculate_overall_rating
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_product, only: %i[new create]

  def new
    @review = @product.reviews.new
  end

  def create
    @review = @product.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.js { redirect_to products_url, notice: 'Review was successfully created.' }
      else
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:reviewer_name, :written_review, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def rating_array(product)
    rating = product.overall_rating || 0
    (1..5).map do |star|
      value = rating - star
      if value >= 0
        'bi-star-fill'
      else
        value <= -1 ? 'bi-star' : 'bi-star-half'
      end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reviews3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>

    <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="border rounded p-3 col-3 g-2">
  <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="150" fill="currentColor" class="" viewBox="0 0 16 16">
    <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
    <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
  </svg>

  <p>
    <%= product.name %>
  </p>

  <p>
    <%= product.description %>
  </p>

  <div class="container text-center p-4" title="<%= product.overall_rating.to_f %>">
    <div class="row">
      <% rating_array(product).each do |icon_class| %>
        <div class="col">
          <i class="<%= icon_class %>"></i>
        </div>
      <% end %>
    </div>
  </div>
  <%# <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#reviewModal">
    Add review
  </button> %>
  <%= button_to "New review", new_product_review_path(product), method: :get, remote: true %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<main class="container">
    <div class="d-flex justify-content-between align-items-center my-4">
      <h2 class="h2 text-center">Products</h2>
    </div>

    <div id="items" class="row g-3">
      <%= render @products %>
    </div>
</main>

app/views/reviews/_form.html.erb
<%= form_with(model: [product, review], local: false) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div class="container">

      <div class="mb-3">
        <%= form.label 'Your name', style: "display: block" %>
        <%= form.text_field :reviewer_name, size: "50" %>
      </div>

      <div>
        <%= form.label 'Your rating', style: "display: block" %>
        <%= form.number_field :rating, style: "display: none" %>
      </div>
      <div class="container-sm">
        <div class="row justify-content-xs-center">
          <% (1..5).each do |star_id| %>
            <div class="col">
              <button type="button" class="btn" onclick="set_stars(<%= star_id %>);">
                <i id="star_id_<%= star_id %>" class="bi-star"></i>
              </button>
            </div>
          <% end %>
      </div>
     </div>

      <div>
        <%= form.label 'Your review', style: "display: block" %>
        <%= form.text_area :written_review, size: "50" %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/reviews/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New review</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="container">
  <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="150" fill="currentColor" class="" viewBox="0 0 16 16">
    <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
    <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
  </svg>

  <p>
    <%= @product.name %>
  </p>

  <p>
    <%= @product.description %>
  </p>
</div>

<%= render "form", review: @review, product: @product %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review, product: @product %>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/reviews/new.js.erb
jQuery("#reviewModal").find(".modal-content").html("<%= j (render 'new') %>");
set_stars(<%= @review.rating %>);
jQuery("#reviewModal").modal('show');

function set_stars(star_id) {
  jQuery("#review_rating").val(star_id);
  let stars_to_fill = 5 - star_id
  while (star_id > 0) {
    jQuery("#star_id_" + star_id).removeClass("bi-star")
    jQuery("#star_id_" + star_id).addClass("bi-star-fill")
    star_id--;
  }

  while (stars_to_fill > 0) {
    jQuery("#star_id_" + (6 - stars_to_fill)).removeClass("bi-star-fill")
    jQuery("#star_id_" + (6 - stars_to_fill)).addClass("bi-star")
    stars_to_fill--;
  }
}

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>